// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List the signed-in user's clients. Supports search by name/email and pagination.",
  inputSchema: {
    search: z.string().optional().describe("Case-insensitive substring match on name or email."),
    status: z.enum(["active", "archived"]).optional().describe("Filter by status. Defaults to active."),
    limit: z.number().int().min(1).max(200).optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("clients").select("id, name, email, phone, status, notes, base_price, created_at").eq("status", status ?? "active").order("name", { ascending: true }).limit(limit ?? 50);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`name.ilike.${s},email.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_appointments_default = defineTool2({
  name: "list_appointments",
  title: "List appointments",
  description: "List the signed-in user's appointments in a date range, optionally filtered by client or status.",
  inputSchema: {
    from: z2.string().describe("ISO date/datetime lower bound (inclusive) for scheduled_at."),
    to: z2.string().describe("ISO date/datetime upper bound (exclusive) for scheduled_at."),
    client_id: z2.string().uuid().optional().describe("Only return appointments for this client id."),
    status: z2.enum(["scheduled", "completed", "cancelled"]).optional().describe("Filter by appointment status."),
    limit: z2.number().int().min(1).max(500).optional().describe("Max results (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, client_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("appointments").select("id, client_id, service_id, scheduled_at, duration_minutes, status, payment_status, price, notes").gte("scheduled_at", from).lt("scheduled_at", to).order("scheduled_at", { ascending: true }).limit(limit ?? 100);
    if (client_id) q = q.eq("client_id", client_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/finance-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var finance_summary_default = defineTool3({
  name: "finance_summary",
  title: "Finance summary",
  description: "Sum income and expenses for the signed-in user over a date range and return net profit.",
  inputSchema: {
    from: z3.string().describe("ISO date lower bound (inclusive) for the `date` column."),
    to: z3.string().describe("ISO date upper bound (inclusive) for the `date` column.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const [incomeRes, expenseRes] = await Promise.all([
      sb.from("income").select("amount, date, source, status").gte("date", from).lte("date", to),
      sb.from("expenses").select("amount, date, category, payment_status").gte("date", from).lte("date", to)
    ]);
    if (incomeRes.error) return { content: [{ type: "text", text: incomeRes.error.message }], isError: true };
    if (expenseRes.error) return { content: [{ type: "text", text: expenseRes.error.message }], isError: true };
    const income = (incomeRes.data ?? []).reduce((s, r) => s + Number(r.amount || 0), 0);
    const expenses = (expenseRes.data ?? []).reduce((s, r) => s + Number(r.amount || 0), 0);
    const summary = {
      from,
      to,
      income_total: income,
      expense_total: expenses,
      net: income - expenses,
      income_count: incomeRes.data?.length ?? 0,
      expense_count: expenseRes.data?.length ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/create-client.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_client_default = defineTool4({
  name: "create_client",
  title: "Create client",
  description: "Create a new client record for the signed-in user.",
  inputSchema: {
    name: z4.string().trim().min(1).describe("Client display name."),
    email: z4.string().email().optional().describe("Client email (optional)."),
    phone: z4.string().optional().describe("Client phone (optional)."),
    notes: z4.string().optional().describe("Free-form notes (optional)."),
    base_price: z4.number().nonnegative().optional().describe("Default per-session price (optional).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ name, email, phone, notes, base_price }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("clients").insert({
      user_id: ctx.getUserId(),
      name,
      email: email ?? null,
      phone: phone ?? null,
      notes: notes ?? null,
      base_price: base_price ?? null
    }).select("id, name, email, phone, notes, base_price, status, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { client: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rxculneqqaziutulnocs";
var mcp_default = defineMcp({
  name: "solo-bizz-mcp",
  title: "Solo Bizz",
  version: "0.1.0",
  instructions: "Tools for the signed-in Solo Bizz user. Use these to look up clients, upcoming or past appointments, income/expense totals, and to create new client records. All data is scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, list_appointments_default, finance_summary_default, create_client_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
