INSERT INTO public.support_articles (module, slug, language, title, body, is_published, sort_order) VALUES
('Getting Started','getting-started-overview','en','What Solo .Bizz does and where things live','Solo .Bizz is a workspace for private practitioners (psychologists, therapists, coaches, tutors).
Main navigation:
- Dashboard: overview of upcoming sessions, income and unpaid items.
- Calendar: sessions, day off, incoming booking requests.
- Clients: client records, contact details, session history, prepaid balance.
- Groups: group clients and group sessions.
- Services: the services you offer with price and duration.
- Finances: income, expenses, payment audit, break-even, finance settings.
- Settings: profile, practice profile, language, currency, notifications, subscription.
The onboarding widget guides new users through the first steps and can be minimised.',true,1),
('Onboarding','onboarding-steps','en','Onboarding checklist','The onboarding widget appears in the app until the steps are done. Each step links straight to the page where the action happens (for example Calendar with the new-session dialog, or Expenses with the new-expense dialog). A completed step stays completed. Closing or minimising the widget keeps it closed for the current session. Solo .Bizz never creates demo clients or sessions for you.',true,1),
('Dashboard','dashboard-overview','en','Reading the dashboard','The dashboard shows upcoming sessions, recent activity, income for the current period and unpaid sessions. Clicking a card opens the related page (Calendar, Clients or Finances). Numbers follow the currency set in Finances → Settings.',true,1),
('Calendar','calendar-create-session','en','Create a session','Calendar → pick the day → "New session" (or Clients → select client → Sessions → Create session). Choose client (or group), service, date, start time and duration. The price is taken from the service and can be changed for a single session. Recurring sessions: enable repeat in the session dialog and choose the interval and end; each occurrence can later be edited or cancelled on its own.',true,1),
('Calendar','calendar-day-off','en','Day off and availability','Mark a day off from the Calendar so it is blocked for public booking. Working hours and slot length come from Calendar settings; the public booking page only offers free slots inside them.',true,2),
('Calendar','calendar-requests','en','Incoming booking requests','Requests made through your booking link land in the Incoming Requests inbox; the Calendar toolbar shows a badge with the number waiting. Open a request to confirm or decline it. Confirming creates the session and emails the client.',true,3),
('Clients','clients-create','en','Create and manage a client','Clients → "New client". Name is required; email and phone are optional, but an email is needed to send booking confirmations, reminders or an information agreement. An invalid email is rejected when saving. Open a client to see sessions, payments, prepaid balance and notes. Clients can be archived instead of deleted; a client with sessions cannot be deleted while those sessions exist.',true,1),
('Groups','groups-basics','en','Groups and group sessions','Groups → create a group and add clients to it. Creating a session for a group creates one calendar entry with the group participants; payment is tracked per participant, so one participant can be paid while another is not.',true,1),
('Services','services-basics','en','Services','Services → "New service" with name, duration and price. Services are used as defaults when creating a session and on the public booking page. Changing a service price does not change sessions that already exist.',true,1),
('Booking','booking-link','en','Booking link for clients','Settings → Practice profile holds your public page. Share the booking link with a client; they pick a free slot and submit a request. You confirm it from Incoming Requests. Slots offered come from your calendar settings, existing sessions and days off.',true,1),
('Payments','payments-mark-paid','en','Mark a session paid and prepaid balance','Open the session (Calendar or the client''s session list) and switch its payment status to paid; the amount is recorded as income on that date. For group sessions mark each participant separately. A prepaid balance on the client is used up automatically as sessions are marked paid.',true,1),
('Finances','finances-overview','en','Income, expenses and break-even','Finances → Income lists paid sessions and manual income. Finances → Expenses records business costs. Payment audit shows unpaid or inconsistent items. Break-even compares monthly costs with income. Currency and period settings live in Finances → Settings.',true,1),
('Notifications','notifications-basics','en','Emails and reminders','Clients receive booking confirmations, session reminders and cancellation notices by email when they have an email address. Telegram can be connected from Settings for your own notifications. Reminder timing is configured in settings.',true,1),
('Subscription','subscription-plans','en','Plans and billing','Plans: Free (up to 5 active clients), Solo (up to 20 active clients) and Pro (unlimited). All features are in every plan; only the number of active clients differs. Billing is monthly, quarterly or yearly and is handled by Paddle. A promo code can be entered on the plans page before checkout. Subscriptions renew automatically until cancelled; cancelling keeps access until the end of the paid period.',true,1),
('Settings','settings-language-currency','en','Language, currency and profile','Settings → change interface language (English, Ukrainian, Polish, French). Currency for finances is set in Finances → Settings. Practice profile controls what clients see on the public booking page.',true,1),
('Troubleshooting','troubleshooting-common','en','When something cannot be created, edited or deleted','Common reasons: the client limit of the current plan is reached (upgrade or archive clients); the slot overlaps an existing session or a day off; a required field such as service or duration is empty; the record is referenced by other data (for example a client with sessions) and must be archived instead; the session belongs to a past period that is locked for editing. If the app shows an error message, the assistant can explain that specific code — use "Ask Support" next to the error.',true,1),
('Troubleshooting','troubleshooting-session-expired','en','Signed out or session expired','If the app says your session expired, sign in again. Changes made while signed out are not saved. This protects data if the browser was left open for a long time.',true,2)
ON CONFLICT (slug) DO NOTHING;